apiVersion: v1
kind: Secret
metadata:
  name: auction-app-secrets
  namespace: auction-production
type: Opaque
stringData:
  PORT: "3000"
  NODE_ENV: "production"

  # Session & Secrets
  SESSION_SECRET: "your_super_secret_session_key_here"
  HASH_ID_SECRET: "auction-pro-super-secret"

  # JWT
  ACCESS_TOKEN_SECRET: "your_jwt_access_token_secret_here"
  ACCESS_TOKEN_LIFE: "900000"
  REFRESH_TOKEN_SECRET: "your_jwt_refresh_token_secret_here"
  REFRESH_TOKEN_LIFE: "604800000"

  # TiDB (Database)
  DB_HOST: "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
  DB_PORT: "4000"
  DB_USER: "3376UGxG16S5pvR.root"
  DB_PASSWORD: "AdGF9A7mrpZVKZCH"
  DB_NAME: "Auction"
  DB_SSL: "true"

  # Cloudinary
  CLOUDINARY_CLOUD_NAME: "qbkd6qxg"
  CLOUDINARY_API_KEY: "875713665717554"
  CLOUDINARY_API_SECRET: "nvOfuIoVMsSFbn5fhWyXjsoM9fQ"

  # Pusher
  PUSHER_APP_ID: "2196766"
  PUSHER_KEY: "ea63537bae00c1ea1bea"
  PUSHER_SECRET: "2e479667730db69a0702"
  PUSHER_CLUSTER: "ap2"
